# Stage 1: Build
FROM maven:3.8.8-eclipse-temurin-17-alpine AS build

WORKDIR /app

COPY . .

WORKDIR /app/user-product-service/order-service

RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM openjdk:17-alpine

WORKDIR /app

COPY --from=build /app/user-product-service/order-service/target/order-service-0.0.1.jar /app/app.jar

EXPOSE 8301

ENTRYPOINT ["java", "-jar", "/app/app.jar"]