# Stage 1: Build
FROM maven:3.8.8-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /app/target/user-service-0.0.1.jar app.jar
EXPOSE 8001
ENTRYPOINT ["java", "-jar", "/app.jar"]