name: E-Commerzion - Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  e-commerzion-services:
    runs-on: ubuntu-latest

    services:
      postgres-user-service:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: user_service
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d user_service"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
      postgres-seller-service:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: seller_service
        ports:
          - "5433:5432"
        options: >-
          --health-cmd="pg_isready -U postgres -d seller_service"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create Docker Network
        run: docker network create e-commerzion-network || true
        
      - name: Build User Service
        run: mvn -B clean verify --projects user-service
        working-directory: user-product-service

      - name: Pull and Run User Service App
        run: |
          docker run -d --name user-service-app --network e-commerzion-network -p 8001:8001 \
          kirk006/e-commerzion-user-service-app:latest

      - name: Wait for User Service App to Start
        run: |
          echo "Waiting for user-service-app to start..."
          until curl -s http://localhost:8001/api/v1/users/1; do
            sleep 5
          done
          echo "user-service-app is running."

      - name: Run Integration Tests
        run: mvn -B clean verify --projects seller-service
        working-directory: user-product-service

      - name: Clean Up Docker Containers
        run: |
          docker stop user-service-app seller-service-app || true
          docker rm user-service-app seller-service-app || true

      - name: Clean Up Docker Network
        run: docker network rm e-commerzion-network || true
