name: E-Commerzion - Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build User Service
        run: mvn clean install -DskipTests --projects user-service
        working-directory: user-product-service
        
      - name: Run tests
        run: mvn test
        working-directory: user-product-service

      - name: Package the application
        run: mvn package -DskipTests
        working-directory: user-product-service