name: E-Commerzion - Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build User Service
        run: mvn clean -B test -Dtest=UnitTesting/* --projects user-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db

      - name: Build and Push User Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-app:latest