name: E-Commerzion - Dev Branch

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean -B test -Dtest=UnitTesting/* --projects user-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db

      - name: Build and Push User Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-app:0.0.1
          
  seller-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean -B test -Dtest=UnitTesting/* --projects seller-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-db

      - name: Build and Push Seller Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/seller-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-app:0.0.1
          
  product-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean -B test -Dtest=UnitTesting/* --projects product-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-product-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-product-service-db

      - name: Build and Push Product Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/product-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-product-service-app:0.0.1
  
  order-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean -B test -Dtest=UnitTesting/* --projects order-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-service-db

      - name: Build and Push Order Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/order-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-service-app:0.0.1
          
  order-items-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean -B test -Dtest=UnitTesting/* --projects order-items-service
        working-directory: user-product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-items-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-items-service-db

      - name: Build and Push Order Items Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/order-items-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-order-items-service-app:0.0.1
          
      - name: Pull RabbitMQ Image
        run: docker pull rabbitmq:3.9.11-management-alpine
          
      - name: Tag and Push RabbitMQ Image
        run: |
          docker tag rabbitmq:3.9.11-management-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-rabbitmq
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-rabbitmq
