name: E-Commerzion - Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create Docker Network
        run: docker network create e-commerzion-network || true

      - name: Run PostgreSQL for User Service
        run: |
          docker run -d --name user-service-db --network e-commerzion-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_DB=user_service \
          -p 5432:5432 kirk006/e-commerzion-user-service-db:latest

      - name: Wait for User Service DB to Start
        run: |
          echo "Waiting for user-service-db ..."
          for i in {1..12}; do
            docker exec user-service-db pg_isready -U postgres -d user_service && break
            echo "Still waiting for user-service-db..."
            sleep 5
          done
          echo "User Service database is ready."

      - name: Build User Service
        run: mvn -B clean verify --projects user-service
        working-directory: user-product-service

      - name: Clean Up Docker Containers
        run: |
          docker stop user-service-db || true
          docker rm user-service-db || true

      - name: Clean Up Docker Network
        run: docker network rm e-commerzion-network || true

  seller-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create Docker Network
        run: docker network create e-commerzion-network || true

      - name: Run PostgreSQL for Seller Service DB
        run: |
          docker run -d --name seller-service-db --network e-commerzion-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_DB=seller_service \
          -p 5433:5432 kirk006/e-commerzion-seller-service-db:latest

      - name: Wait for Seller Service DB to Start
        run: |
          echo "Waiting for seller-service-db ..."
          for i in {1..12}; do
            docker exec seller-service-db pg_isready -U postgres -d seller_service && break
            echo "Still waiting for seller-service-db..."
            sleep 5
          done
          echo "Seller Service database is ready."

      - name: Build Seller Service
        run: mvn -B clean verify --projects seller-service
        working-directory: user-product-service

      - name: Clean Up Docker Containers
        run: |
          docker stop seller-service-db || true
          docker rm seller-service-db || true

      - name: Clean Up Docker Network
        run: docker network rm e-commerzion-network || true

  product-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create Docker Network
        run: docker network create e-commerzion-network || true

      - name: Run PostgreSQL Databases
        run: |
          docker run -d --name user-service-db --network e-commerzion-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_DB=user_service \
          -p 5432:5432 kirk006/e-commerzion-user-service-db:latest
          docker run -d --name seller-service-db --network e-commerzion-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_DB=seller_service \
          -p 5433:5432 kirk006/e-commerzion-seller-service-db:latest
          docker run -d --name product-service-db --network e-commerzion-network \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=test \
          -e POSTGRES_DB=product_service \
          -p 5434:5432 postgres:14-alpine

      - name: Wait for PostgreSQL Databases to Start
        run: |
          echo "Waiting for databases..."
          for i in {1..12}; do
            docker exec user-service-db pg_isready -U postgres -d user_service && break
            echo "Still waiting for user-service-db..."
            sleep 5
          done
          for i in {1..12}; do
            docker exec seller-service-db pg_isready -U postgres -d seller_service && break
            echo "Still waiting for seller-service-db..."
            sleep 5
          done
          for i in {1..12}; do
            docker exec product-service-db pg_isready -U postgres -d product_service && break
            echo "Still waiting for product-service-db..."
            sleep 5
          done
          echo "All databases are ready."

      - name: Build Product Service
        run: mvn -B clean verify --projects product-service
        working-directory: user-product-service

      - name: Clean Up Docker Containers
        run: |
          docker stop user-service-db seller-service-db product-service-db || true
          docker rm user-service-db seller-service-db product-service-db || true

      - name: Clean Up Docker Network
        run: docker network rm e-commerzion-network || true
