name: E-Commerzion - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update dev branch
      - name: Update dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      # Step 3: Check if features branch is merged into dev
      - name: Check if features branch is merged into dev
        run: |
          git fetch origin dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Pull and Tag PostgreSQL Base Image
      - name: Pull postgres:14-alpine
        run: |
          docker pull postgres:14-alpine
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db:latest

      - name: Push PostgreSQL Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db:latest

      # Step 6: Build and Push User Service Docker Image
      - name: Build and Push User Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./user-product-service/user-service
          file: Dockerfile.users
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-app:latest

      # Step 7: Run PostgreSQL Container
      - name: Run PostgreSQL Container Locally
        run: |
          docker run -d \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=test \
            -e POSTGRES_DB=user_service \
            -p 5432:5432 \
            --name user-service-db \
            postgres:14-alpine
