name: E-Commerzion - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  ensure-dev-merge:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      - name: Check if features branch is merged into dev
        run: |
          # Fetch latest changes from the dev branch
          git fetch origin dev
          
          # Check if the current branch is merged into dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi
         
      - name: Build and Push User Service Docker Image
        run: |
          docker build -t E-Commerzion-${{ secrets.DOCKER_USERNAME }}/User-Service -f user-service/Dockerfile.users .
          docker push E-Commerzion-${{ secrets.DOCKER_USERNAME }}/User-Service
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: user-product-service
