name: E-Commerzion - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  integration-testing:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure dev branch is updated
      - name: Update dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev
  
      - name: Install Docker (official script)
        run: |
            sudo curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo systemctl enable docker
            sudo systemctl start docker
            docker --version
        
      - name: Run Docker Compose production
        run: |
          docker compose -f docker-compose.prod.yml up -d
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for optimized builds
          
      - name: Install Java 17
        run: |
          sudo apt install -y openjdk-17-jdk
          
      - name: Configure hosts
        run: |
          echo "127.0.0.1 user-service-app" | sudo tee -a /etc/hosts
          echo "127.0.0.1 seller-service-app" | sudo tee -a /etc/hosts
          echo "127.0.0.1 product-service-app" | sudo tee -a /etc/hosts
          echo "127.0.0.1 order-service-app" | sudo tee -a /etc/hosts
          echo "127.0.0.1 order-items-service-app" | sudo tee -a /etc/hosts
          
      - name: Run UserService Integration Tests
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          source /etc/environment
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          mvn clean -B test -Dtest=IntegrationTesting/* --projects user-service
        working-directory: user-product-service  # Replace with your correct directory  
        
      - name: Curl Request Body for User Service
        run : |
          curl -X POST http://user-service-app:8001/api/v1/users/register \
            -H "Content-Type: application/json" \
            -d '{
                "name": "John Doe",
                "username": "jdoe@gmail.com",
                "password": "test",
                "confirmPassword": "test"
            }'
          curl -X POST http://user-service-app:8001/api/v1/users/register \
            -H "Content-Type: application/json" \
            -d '{
                "name": "Kirk Mendoza",
                "username": "kirkmendoza9@gmail.com",
                "password": "test",
                "confirmPassword": "test"
            }'
        
      - name: Curl Request Body for Seller Service
        run: |
          curl -X POST http://seller-service-app:8101/api/v1/sellers/register \
            -H "Content-Type: application/json" \
            -d '{
                "userId": 2,
                "sellerName": "Kirk Mendoza",
                "storeName": "K Tech Shop",
                "email": "kirkmendoza9@gmail.com",
                "phoneNumber": "093098001034",
                "location": "Kirk St.",
                "photoUrl": "https://kirk.dev.com"
            }'
        
      - name: Run SellerService Integration Tests
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          source /etc/environment
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          mvn clean -B test -Dtest=IntegrationTesting/* --projects seller-service
        working-directory: user-product-service  # Replace with your correct directory  
        
      - name: Run ProductService Integration Tests
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          source /etc/environment
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          mvn clean -B test -Dtest=IntegrationTesting/* --projects product-service
        working-directory: user-product-service  # Replace with your correct directory 
        
      - name: Clean up Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.prod.yml down
