name: E-Commerzion - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Check if features branch is merged into dev
      - name: Check branch merge status
        run: |
          git fetch origin dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi

      # Step 3: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.31.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 5: Run Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml up -d

      # Step 6: Integration Test
      - name: Run Integration Tests
        run: mvn clean -B test -Dtest=IntegrationTesting/* --projects seller-service
        working-directory: user-product-service

      # Step 7: Cleanup (Optional but recommended)
      - name: Clean up Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.prod.yml down
