name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure dev branch is updated
      - name: Update dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      # Step 3: Check if features branch is merged into dev
      - name: Check branch merge status
        run: |
          git fetch origin dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi

      # Step 4: Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Pull and Push PostgreSQL image
      - name: Pull postgres:14-alpine
        run: docker pull postgres:14-alpine

      - name: Tag and Push PostgreSQL Image for User Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-db

      # Step 6: Build and Push User Service Docker Image
      - name: Build and Push User Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/user-service/Dockerfile.users
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-user-service-app:latest

      # Step 7: Tag and Push PostgreSQL Image for Seller Service
      - name: Tag and Push PostgreSQL Image for Seller Service
        run: |
          docker tag postgres:14-alpine ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-db
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-db

      # Step 8: Build and Push Seller Service Docker Image
      - name: Build and Push Seller Service Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: user-product-service/seller-service/Dockerfile.sellers
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerzion-seller-service-app:latest
