name: E-Commerzion - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure dev branch is updated
      - name: Update dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      # Step 3: Check if features branch is merged into dev
      - name: Check branch merge status
        run: |
          git fetch origin dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi

      # Step 4: Build and run services using docker-compose.prod.yml
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml up -d
          
      - name: Check integration test
        run: mvn clean -B test -Dtest=IntegrationTesting/* --projects seller-service
        working-directory: user-product-service
