name: E-Commerzion CI/CD with Maven - Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  ensure-dev-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Check if the branch is merged into dev
      - name: Check if branch is merged into dev
        run: |
          # Fetch latest changes from the dev branch
          git fetch origin dev
          
          # Check if the current branch is merged into dev
          if ! git merge-base --is-ancestor origin/dev HEAD; then
            echo "This branch must be merged into 'dev' before being merged into 'main'."
            exit 1
          fi
